### ISSUE TITLE
Error fetching metadata

### ISSUE THREAD

**Issue by ShouZiJun** [vipexv/minimal-hud#2]
F8 console error message
SCRIPT ERROR: @minimal-hud/modules/frameworks/qb.lua:17: attempt to index a nil value (local 'metadata')

Framework: QBCore 1.2.6
![FiveM® by Cfx re - 由QBCore框架构建的SaPixel丧尸生存服务器! 2024_9_14 4_41_20](https://github.com/user-attachments/assets/5cf1ae2d-9e4a-40d3-b67c-2c8757d12203)

**Comment by vipexv** [comment]
I don't know that much about QB Core but this isn't an issue on my end since from what i've tested it's seemed to work and it seems to work for other people using QB as well, i don't provide too much support for frameworks, just basic support.

I'll try to test it again today or tomorrow.

**Comment by ShouZiJun** [comment]
If I fix this, I'll leave a message here

**Comment by ShouZiJun** [comment]
If I fix this, I'll leave a message here

**Comment by vipexv** [comment]
This will be fixed in 1.0.5

**Comment by vipexv** [comment]
This issue has been fixed in 1.0.5
