### ISSUE TITLE
Ejecting From Car freezes speedometer

### ISSUE THREAD

**Issue by TrilogyRPz** [vipexv/minimal-hud#3]
Crashing and ejecting From car seems to freeze the speedometer on the current speed you were at when you crashed.

**Comment by vipexv** [comment]
Mind sending me a video.

Also please go ahead and enable debug mode and send your log of when this happens.

**Comment by vipexv** [comment]
Will be closed due to inactivity, please re-open once you have completed the task i've assigned above.

**Comment by vipexv** [comment]
Fixed in https://github.com/vipexv/minimal-hud/commit/b0c9943ea2f9a002cd10fb8093e305e7bf27a4bc

**Comment by vipexv** [comment]
Fixed in https://github.com/vipexv/minimal-hud/commit/b0c9943ea2f9a002cd10fb8093e305e7bf27a4bc
