### ISSUE TITLE
[BUG] : OX Framework visual error

### ISSUE THREAD

**Issue by ENC4YP7ED** [vipexv/minimal-hud#4]
When the Hud displays food and water 100% the bars are empty.

on the Image the food and water are about 90-100%
![{2AF349C5-F7E5-4F79-96EC-C24DE92BA352}](https://github.com/user-attachments/assets/56cd2aa6-8873-4ff2-851b-991090487a53)

**Comment by vipexv** [comment]
Fixed in f0b2d03

**Comment by vipexv** [comment]
Fixed in https://github.com/vipexv/minimal-hud/commit/f0b2d0339b0f73a998eacd08e5febe6036ca6d57
